export const tools: string;
export const tool: string;
export const action: string;
export const active: string;
export const actions: string;
export const popUp: string;
export const left: string;
export const wobble: string;
export const right: string;
